#if oyur config gives you errors, delete the lines that give yopu errors

[colors.bright]
black = "#6D7070"
blue = "#1BA6FA"
cyan = "#73FBF1"
green = "#B8E466"
magenta = "#A578EA"
red = "#FF4352"
white = "#FEFEF8"
yellow = "#FFD750"

[colors.cursor]
cursor = "#FF261E"
text = "#FF261E"

[colors.normal]
black = "#0d0d0d"
blue = "#1BA6FA"
cyan = "#21DEEF"
green = "#A0E521"
magenta = "#8763B8"
red = "#FF301B"
white = "#EBEBEB"
yellow = "#FFC620"

[colors.primary]
background = "#292C3E"
foreground = "#EBEBEB"

[window]
blur = true
opacity = 0.6

[font]
normal = { family = "CaskaydiaCove NF"}
